INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'09', N'อนุสรณ์สถาน', N'ANUSORN SATHAN')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'01', N'ดินแดง', N'DIN DAENG')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'02', N'สุทธิสาร', N'SUTHISARN')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'03', N'ลาดพร้าว', N'LAD PRAO')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'04', N'รัชดาภิเษก', N'RATCHADA PHISEK')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'05', N'บางเขน', N'BANGKHEN')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'06', N'แจ้งวัฒนะ', N'CHANGEWATTANA')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'07', N'หลักสี่', N'LAKSI')
INSERT [dbo].[TSB] ([TSBId], [TSB_Th_Name], [TSB_Eng_name]) VALUES (N'08', N'ดอนเมือง', N'DON MUANG')