### Save TSB Credit Balance
POST http://localhost:8000/api/account/tsbcredit/save
content-type: application/json

{
    "tsbId": "09",
    "amnt1": 2000,
    "amnt2": 2000,
    "amnt5": 9000,
    "amnt10": 1000,
    "amnt20": 1000,
    "amnt50": 1000,
    "amnt100": 1000,
    "amnt500": 1000,
    "amnt1000": 1000,
    "updatedate": "2021-02-20:13:03.112Z",
    "remark" : null
    
}


### Gets TSB Credit Balance
POST http://localhost:8000/api/account/tsbcredit
content-type: application/json

{
   
}

### Save User Credit on Job
POST http://localhost:8000/api/account/UserCredit/save
content-type: application/json

{
    "tsbId": "09",
    "userId": "00111",
    "userprefix": "นาย",
    "userfirstname": "หัสกร",
    "userlastname": "ทิพยไพศาล",
    "bagno": "1245",
    "credit": 10000,
    "flag": 0,
    "creditdate": "2021-02-20:13:03.112Z"
}

### Gets User On Job Credit by TSB
POST http://localhost:8000/api/account/usercredit/search
content-type: application/json

{
   "tsbId": "09"
}


### Save Request  Head
POST http://localhost:8000/api/account/request/save
content-type: application/json

{
    "requestid": 1 ,
    "tsbId": "08",
    "exchangebht" : 20000,
    "borrowbht" : 0,
    "additionalbht" : 0,
    "periodbegin" : null,
    "periodend" : null,
    "remark" : "ทดสอบ",
    "finishflag" : 0 ,
    "userid" : "00444" ,
    "tranactiondate" : "2021-04-13:22:03.112Z" ,
    "status" : "R"


}


### Save Request  Detail
POST http://localhost:8000/api/account/request/savedetail
content-type: application/json

{
    "requestid": 1 ,
    "tsbId": "09",
    "currencydenomid" : 6,
    "currencyvalue" : 5000,
    "currencycount" : 500

}


### Account get request list
POST http://localhost:8000/api/account/request/getlist
content-type: application/json

{
    "status": "R" 

}


### Account get request detail
POST http://localhost:8000/api/account/request/getdetail
content-type: application/json

{
    "requestid": 1 ,
    "tsbId": "09"

}


### Account Save Approve request detail
POST http://localhost:8000/api/account/request/approve
content-type: application/json

{
     "requestid": 1 ,
    "tsbId": "09",
    "currencydenomid" : 6,
    "currencyvalue" : 5000,
    "currencycount" : 500

}


### TSB get Approve request update
POST http://localhost:8000/api/account/request/getapprove
content-type: application/json

{
     "tsbId": "09",
    "transdate" : "2021-04-13:00:00.000Z" 

}


### TSB get Approve request detail
POST http://localhost:8000/api/account/request/getapprovedetail
content-type: application/json

{
    "requestid": 1 ,
    "tsbId": "09"

}


### Get Approve TSB Credit List
POST http://localhost:8000/api/account/appcredit/list
content-type: application/json

{
    
}


### Get  TSB Aprove Credit Transaction List
POST http://localhost:8000/api/account/appcredit/translist
content-type: application/json

{
    "tsbId": "09"
}


### Get  TSB Aprove Credit Transaction List
POST http://localhost:8000/api/account/appcredit/savetrans
content-type: application/json

{
    "tsbId": "09" ,
    "creapprove" : 200000 ,
    "creactual" : 0 ,
    "approvetype" : "I" ,
    "filename" : "09In.pdf" ,
    "approveby" : "00444" ,
    "approvedate" : "2021-05-08:00:00.000Z" 
}