### Send user attendace begin
POST http://localhost:3000/api/TCT/LaneAttendance/save
content-type: application/json

{
    "jobid": "D0001",
    "tsbid": "311",
    "plazaid": "3101",
    "laneid": "DD02",
    "userid": "14124",
    "boj": "2020-08-06T19:30:43.511Z",
    "eoj": null
}

### Send user attendace end
POST http://localhost:3000/api/TCT/LaneAttendance/save
content-type: application/json

{
    "jobid": "D0001",
    "tsbid": "311",
    "plazaid": "3101",
    "laneid": "DD02",
    "userid": "14124",
    "boj": null,
    "eoj": "2020-08-06T20:18:43.511Z"
}
