### Gets all user coupons that assigned by TA (POST) coupon 35
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "00111",
    "coupontype": "35"
}

### Gets all user coupons that assigned by TA (POST) coupon 80
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "14124",
    "coupontype": "80"
}

### Gets all user coupons that assigned by TA (POST) coupon all
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "14124",
    "coupontype": null
}

### Send user coupon sold to TA server (POST)
POST http://localhost:8000/api/TCT/coupons/sold
content-type: application/json

{
    "tsbid": "09",
    "plazaid": "092",
    "laneid": "AN11",
    "coupontype": "35",
    "serialno": "ข003997",
    "price": 665,
    "userid": "00111",
    "solddate": "2021-01-01T10:54:43.511Z"
}

