### Gets all user coupons that assigned by TA (POST) coupon 35
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "00111",
    "coupontype": "35"
}

### Gets all user coupons that assigned by TA (POST) coupon 80
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "14124",
    "coupontype": "80"
}

### Gets all user coupons that assigned by TA (POST) coupon all
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "14124",
    "coupontype": null
}

### Send user coupon 35 sold to TA server (POST)
POST http://localhost:8000/api/TCT/coupons/sold
content-type: application/json

{
    "tsbid": "09",
    "plazaid": "091",
    "laneid": "AN02",
    "coupontype": "35",
    "serialno": "ข009872",
    "price": 665,
    "userid": "20001",
    "solddate": "2021-02-20:12:20.511Z",
    "paytypeid" : 2,
    "paytypename" : "EMV",
    "edcdatetime" : "2021-02-20:12:20.511Z",
    "edcterminalid" : "12345678",
    "edccardno" : "C2345678",
    "edcamount" : 665,
    "edcref1" : "1254554",
    "edcref2" : "652658-2",
    "edcref3" : "C5598-5"
}

### Send user coupon 80 sold to TA server (POST)
POST http://localhost:8000/api/TCT/coupons/sold
content-type: application/json

{
    "tsbid": "09",
    "plazaid": "092",
    "laneid": "AN12",
    "coupontype": "80",
    "serialno": "C000745",
    "price": 1520,
    "userid": "20001",
    "solddate": "2021-02-20:12:22.511Z",
    "paytypeid" : 1,
    "paytypename" : "Cash",
    "edcdatetime" : "2021-02-20:12:22.511Z",
    "edcterminalid" : "12345678",
    "edccardno" : "C2345678",
    "edcamount" : 1520,
    "edcref1" : null,
    "edcref2" : null,
    "edcref3" : null
}

