### Gets all user coupons that assigned by TA (POST) coupon 35
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "00111",
    "coupontype": "35"
}

### Gets all user coupons that assigned by TA (POST) coupon 80
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "14124",
    "coupontype": "80"
}

### Gets all user coupons that assigned by TA (POST) coupon all
POST http://localhost:8000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "09",
    "userId": "14124",
    "coupontype": null
}

### Send user coupon 35 sold to TA server (POST)
POST http://localhost:8000/api/TCT/coupons/sold
content-type: application/json

{
    "tsbid": "09",
    "plazaid": "091",
    "laneid": "AN01",
    "coupontype": "35",
    "serialno": "ข003996",
    "price": 665,
    "userid": "20001",
    "solddate": "2021-02-18T21:01:43.511Z"
}

### Send user coupon 80 sold to TA server (POST)
POST http://localhost:8000/api/TCT/coupons/sold
content-type: application/json

{
    "tsbid": "09",
    "plazaid": "091",
    "laneid": "AN01",
    "coupontype": "80",
    "serialno": "C000684",
    "price": 1520,
    "userid": "20001",
    "solddate": "2021-02-18T21:03:03.511Z"
}

