### common variables
@sapLocalurl='https://localhost:8000/sap/opu/odata/SAP/ZOD_MM_INTERFACE_SRV/RESERVHSet'
@sapUATurl='https://172.16.202.138:44380/sap/opu/odata/SAP/ZOD_MM_INTERFACE_SRV/RESERVHSet'

@username=api_user
@password=DMTinf#2023

### Create Reservation Items

POST {{@sapUATurl}}
content-type: application/json
Authorization: Basic {{username}} {{password}}
SAP-Client: 300

{
    "BASE_DATE": "20230721",
    "MOVEMENT_TYPE": "311",
    "GOODS_RECIPIENT": "TADD20230001",
    "RECEIVING_STOR": "CCDD",
    "ITEM": [
        {
            "ITEM_NUMBER": "1",
            "MATERIAL_NUM": "31000001",
            "MATERIAL_DESCRIPTION": "เล่มคูปอง 80 บาท",
            "QUANTITY": "100",
            "UNIT_OF_MEASURE": "BOK",
            "PLANT": "1010",
            "FROM_STOR": "CDMT"
        }
    ],
    "RETURN":[]
}

