### common variables
@username=api_user
@password=DMTinf#2023

### Gets Get Reservation by status
### parameters:
### sendresult: NULL รอส่ง, A ไม่ระบุ, S สำเร็จ, E ไม่สำเร็จ
### transfer: NULL ไม่ระบุ, N รอใบเบิก, Y รับโอน

POST http://localhost:8000/api/secure/reservation/search
content-type: application/json
Authorization: Basic {{username}} {{password}}
SAP-Client: 300

{
    "basedate": "20230826",
    "sendresult": "A",
    "transfer": "Y"
}
