### common variables
@username=api_user
@password=DMTinf#2023

### Gets Storage Location

POST http://localhost:8000/api/secure/master/storage/gets
content-type: application/json
Authorization: Basic {{username}} {{password}}
SAP-Client: 300

{
    "tsbId": "09"
}
