### TA Save Coupon 
POST http://localhost:3000/dmt-scw/api/tod/jobList
content-type: application/json

{
    "networkId": 31,
    "plazaId": 3101,
    "staffId": "14124"
}


### EMULATOR TEST FUNCTIONS

### BOJ
POST http://localhost:3000/dmt-scw/api/emu/boj
content-type: application/json

{
    "networkId": 31,
    "plazaId": 15,
    "laneId": 6,
    "jobNo": 1,
    "staffId": "00112"
}

### EOJ
POST http://localhost:3000/dmt-scw/api/emu/eoj
content-type: application/json

{
    "networkId": 31,
    "plazaId": 15,
    "laneId": 4,
    "jobNo": 1,
    "staffId": "00112"
}
