### TA Save Coupon 
POST http://localhost:3000/api/users/coupons/save
content-type: application/json

{
    "couponpk": 12,
    "transactionid": 444,
    "transactiondate": "2020-12-25T18:25:43.511Z",
    "tsbid": "311",
    "coupontype": "35",
    "serialno": "ข002213",
    "price": 665,
    "userid": "00111",
    "userreceivedate": "2020-12-25T18:25:43.511Z",
    "Couponstatus": "2",
    "solddate": null,
    "soldby": null,
    "finishflag": "1"
}


### Gets all TSB coupons Data
POST http://localhost:3000/api/users/coupons/getlist
content-type: application/json

{
    "TSBId": "311",
    "UserId": null,
    "TransactionType": 1,
    "Coupontype": null
}
