### TA Save Coupon 
POST http://localhost:3000/api/users/coupons/save
content-type: application/json

{
    "couponpk": 5,
    "transactionid": 555,
    "transactiondate": "2020-12-25T18:25:43.511Z",
    "tsbid": "09",
    "coupontype": "35",
    "serialno": "ข003904",
    "price": 665,
    "userid": "00111",
    "userreceivedate": "2020-12-25T18:25:43.511Z",
    "Couponstatus": "2",
    "solddate": null,
    "soldby": null,
    "finishflag": "1",
    "sendtaflag": 1
}


### Gets New TSB coupons data (only newly data which is flag is 0)
POST http://localhost:8000/api/users/coupons/getlist
content-type: application/json

{
    "TSBId": "09",
    "UserId": null,
    "TransactionType": null,
    "Coupontype": null,
    "flag": 0
}


### Gets All TSB coupons data
POST http://localhost:3000/api/users/coupons/getlist
content-type: application/json

{
    "TSBId": "09",
    "UserId": null,
    "TransactionType": 1,
    "Coupontype": 35,
    "flag": null
}


### Update TSB coupons flags (call when read and stored to local database to mark flag to 1).
POST http://localhost:3000/api/TA/coupons/updatereceive
content-type: application/json

{
    "serialno": "ข003915"
}


### Gets New TSB coupons data (pagination) - (only newly data which is flag is 0)
POST http://localhost:8000/api/users/coupons/getlist2
content-type: application/json

{
    "TSBId": "09",
    "UserId": null,
    "TransactionType": null,
    "Coupontype": null,
    "flag": 0,
    "pageNum": 1,
    "rowsPerPage": 10
}

### Gets All TSB coupons data (pagination) - Example to get page 2
POST http://localhost:8000/api/users/coupons/getlist2
content-type: application/json

{
    "TSBId": "09",
    "UserId": null,
    "TransactionType": null,
    "Coupontype": null,
    "flag": null,
    "pageNum": 1,
    "rowsPerPage": 10
}

### TA Inquiry Coupon Sell -- 1
POST http://localhost:8000/api/TA/coupons/inquiry
content-type: application/json

{
    "SAPItemCode": "C35",
    "SAPIntrSerial": null,
    "SAPTransferNo": null,
    "ItemStatusDigit": null,
    "TollWayId": 9,
    "WorkingDateFrom": null,
    "WorkingDateTo": null,
    "SAPARInvoice": "",
    "ShiftId": null
}

### TA Inquiry Coupon Sell -- 2
POST http://localhost:8000/api/TA/coupons/inquiry
content-type: application/json

{
    "SAPItemCode": "",
    "SAPIntrSerial": null,
    "SAPTransferNo": null,
    "ItemStatusDigit": null,
    "TollWayId": 1,
    "WorkingDateFrom": "2020-01-10T18:25:43.511Z",
    "WorkingDateTo": null,
    "SAPARInvoice": "",
    "ShiftId": null
}

### TA Inquiry Coupon Sell -- 3
POST http://localhost:8000/api/TA/coupons/inquiry
content-type: application/json

{
    "SAPItemCode": "C35",
    "SAPIntrSerial": null,
    "SAPTransferNo": null,
    "ItemStatusDigit": null,
    "TollWayId": 9,
    "WorkingDateFrom": null,
    "WorkingDateTo": null,
    "SAPARInvoice": "",
    "ShiftId": 0
}
