### Gets all user coupons that assigned by TA (POST) coupon 35
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "311",
    "userId": "14124",
    "coupontype": "35"
}

### Gets all user coupons that assigned by TA (POST) coupon 80
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "311",
    "userId": "14124",
    "coupontype": "80"
}

### Gets all user coupons that assigned by TA (POST) coupon all
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "",
    "userId": "14124",
    "coupontype": null
}

### Send user coupon to TA server (POST) - Incompleted sp not call some data is not saved.
POST http://localhost:3000/api/TCT/coupons/sold
content-type: application/json

{
    "tsbid": "311",
    "plazaid": "3101",
    "laneid": "DD01",
    "coupontype": "35",
    "serialno": "ข002202",
    "price": 665,
    "userid": "14124",
   "solddate": "2020-08-10T18:25:43.511Z"
}


### Gets all TSB coupons Data
POST http://localhost:3000/api/users/coupons/getlist
content-type: application/json

{
    "tsbid": "311",
    "userId": null,
    "transactiontype": 2,
    "coupontype": 35
}


### Gets all TSB coupons Data
POST http://localhost:8000/api/TA/coupons/editserialno
content-type: application/json

{
    "tsbid": "09",
    "oldserialno": "C000527",
    "newserialno": "C000603"
}

