### Send user coupon to TA server (POST) - Incompleted sp not call some data is not saved.
POST http://localhost:3000/api/users/coupons/save
content-type: application/json

{
    "couponpk": null,
    "transactionid": 122,
    "transactiondate": "2020-08-06T18:25:43.511Z",
    "tsbid": "311",
    "coupontype": "35",
    "serialno": "C112202",
    "price": 1268,
    "userid": "14124",
    "userreceivedate": "2020-08-06T18:25:43.511Z",
    "Couponstatus": "1",
    "solddate": "2020-08-06T18:25:43.511Z",
    "soldby": null,
    "finishflag": "1"
}

