### Users (all) (POST)
GET http://localhost:3000/api/users
content-type: application/json

{
}

### Users (one) (GET)
GET http://localhost:3000/api/users/14566


### Users (one) (POST)
POST http://localhost:3000/api/users
content-type: application/json

{
    "staffId": "14566"
}