### Gets all user coupons that assigned by TA (POST) coupon 35
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "311",
    "userId": null,
    "coupontype": "35"
}

### Gets all user coupons that assigned by TA (POST) coupon 80
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "311",
    "userId": null,
    "coupontype": "80"
}

### Gets all user coupons that assigned by TA (POST) coupon all
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "311",
    "userId": null,
    "coupontype": ""
}

### Gets all user coupons that assigned by TA (POST) coupon all
POST http://localhost:3000/api/users/coupons/search
content-type: application/json

{
    "tsbId": "311",
    "userId": null,
    "coupontype": null
}

