UPDATE TSB
SET TSB_WhsCode = 'DD'
WHERE TSB.TSBId = '01';

UPDATE TSB
SET TSB_WhsCode = 'SS'
WHERE TSB.TSBId = '02';

UPDATE TSB
SET TSB_WhsCode = 'LP'
WHERE TSB.TSBId = '03';

UPDATE TSB
SET TSB_WhsCode = 'RP'
WHERE TSB.TSBId = '04';

UPDATE TSB
SET TSB_WhsCode = 'BK'
WHERE TSB.TSBId = '05';

UPDATE TSB
SET TSB_WhsCode = 'CW'
WHERE TSB.TSBId = '06';

UPDATE TSB
SET TSB_WhsCode = 'LK'
WHERE TSB.TSBId = '07';

UPDATE TSB
SET TSB_WhsCode = 'DM'
WHERE TSB.TSBId = '08';

UPDATE TSB
SET TSB_WhsCode = 'AN'
WHERE TSB.TSBId = '09';